### ISSUE TITLE
[ISSUE] Issue with `databricks_v1.16.1` resource: databricks_directory

### ISSUE THREAD

**Issue by Postarion** [databricks/terraform-provider-databricks#2318]
Hi,

During Terraform Plan my plugin crashed because of too big int value in object id in the state file.
Here is Error:
```hcl
Stack trace from the terraform-provider-databricks_v1.16.1.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "4387108104317548": value out of range

goroutine 114 [running]:
form-provider-databricks/vendor/google.golang.org/grpc/server.go:1345 +0xed7
google.golang.org/grpc.(*Server).handleStream(0x12cc4360, {0x112dbf8, 0x12f22000}, 0x131b83c0, 0x0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1722 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:966 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:964 +0x25f

Error: The terraform-provider-databricks_v1.16.1.exe plugin crashed!
```
Here is state file value that caused error:
![image](https://github.com/databricks/terraform-provider-databricks/assets/45292352/92f99bad-d3e1-49bb-b577-156e2d50b718)

### Configuration
```hcl
terraform {
  required_version = ">=0.12"

  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "=1.16.1"
    }
  }
  backend "azurerm"{}
}

provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.this.id
}

variable "notebook_folder_list" {
  type        = list(any)
  description = "List of folders inside STAR project on databricks"
  default = ["/xxx/yyyy", "/aaa/bbb", "/ccc/ddd"]
}

resource "databricks_directory" "this" {
  for_each = toset(var.notebook_folder_list)
  path     = "${each.value}"
}
```

**Comment by alexott** [comment]
Please use 64-bit version of provider & Terraform...

**Comment by Postarion** [comment]
It helped, thank you :)
